Repository thakira-dz/3as-terminology, pull requests merged in 2025-05, with the labels that each got.

#16 Update README.md
  README.md
Labels: meta-fix

#18 enhancement in in the typo
  unit-1/geography.md
Labels: geography, unit-1

#19 enhance labels in issues if it's typed in english!
  .github/issue-labeler.yml
Labels: enhancement

#21 Mouadhbendjedidi-patch-2
  .github/ISSUE_TEMPLATE/meta-issue
Labels: enhancement

#20 update(meta): enhance the README.md
  README.md
Labels: meta-fix

#25 Update!: transform this repo into a source repo for these terminologies!
  README.ar.md
  README.md
  unit-1/geography.md
  unit-1/history-characters.md
  unit-1/history-dates.md
  unit-1/history.md
  unit-2/geography.md
  unit-2/history-characters.md
  unit-2/history-dates.md
  unit-2/history.md
  unit-3/geography.md
  unit-3/history-characters.md
  unit-3/history-dates.md
  unit-3/history.md
Labels: history, geography, unit-1, unit-2, unit-3, meta-fix

#29 fix(github actions): fixed the body of the release
  .github/workflows/auto-release.yml
  .github/workflows/converter.yml
Labels: enhancement

#30 docs: Updating README files
  README.ar.md
  README.md
Labels: meta-fix

#31 Update README.ar.md
  README.ar.md
  README.md
Labels: meta-fix

#32 Update README.ar.md
  README.ar.md
  README.md
Labels: meta-fix

#34 Update geography.md
  unit-2/geography.md
Labels: geography, unit-2

#35 update(geography): delete duplication!
  unit-3/geography.md
Labels: geography, unit-3
